### ISSUE TITLE
Not working on Alpine

### ISSUE THREAD

**Issue by lon9** [acrcloud/acrcloud_sdk_python#14]
I tried to use the library on Alpine linux, but the error was occurred.

```
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/acrcloud/recognizer.py", line 21, in <module>
    import acrcloud_extr_tool
ImportError: Error relocating /usr/local/lib/python3.7/site-packages/acrcloud/acrcloud_extr_tool.so: __isnan: symbol not found
```

## Procedure

```
docker run --rm -it python:alpine ash
apk add --no-cache git libstdc++
python -m pip install git+https://github.com/acrcloud/acrcloud_sdk_python
python
from acrcloud.recognizer import ACRCloudRecognizer
```

Can I use it on Alpine?
Please let me know the procedure or Dockerfile to use it on Alpine linux.

**Comment by JPery** [comment]
It seems like they are working on a new version, making the external tool compatible with Alpine Linux: https://github.com/acrcloud/acrcloud_extr_tools/blob/master/acrcloud_extr_linux_alpine

**Comment by qiuxuewen** [comment]
> I tried to use the library on Alpine linux, but the error was occurred.
> 
> ```
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.7/site-packages/acrcloud/recognizer.py", line 21, in <module>
>     import acrcloud_extr_tool
> ImportError: Error relocating /usr/local/lib/python3.7/site-packages/acrcloud/acrcloud_extr_tool.so: __isnan: symbol not found
> ```
> 
> ## Procedure
> ```
> docker run --rm -it python:alpine ash
> apk add --no-cache git libstdc++
> python -m pip install git+https://github.com/acrcloud/acrcloud_sdk_python
> python
> from acrcloud.recognizer import ACRCloudRecognizer
> ```
> 
> Can I use it on Alpine?
> Please let me know the procedure or Dockerfile to use it on Alpine linux.

please try https://github.com/acrcloud/acrcloud_sdk_python/tree/master/docker_alpine.
