### ISSUE TITLE
how to fix Decode Audio Error

### ISSUE THREAD

**Issue by Mohammadwh** [acrcloud/acrcloud_sdk_python#17]
hello 
my code have Decode Audio Error error
file format is ogg

**Comment by qiuxuewen** [comment]
> hello
> my code have Decode Audio Error error
> file format is ogg

Could you send me some examples, support@acrcloud.com.

**Comment by TBoyInPuna** [comment]
I have the same or a similar issue.

![Shell](https://user-images.githubusercontent.com/23587709/226479616-92754b00-7c4d-4809-8e61-14a29e9bf839.png)
![Source](https://user-images.githubusercontent.com/23587709/226479634-3ea8acaf-df15-43b8-a856-6ba6230df3d9.png)

**Comment by TBoyInPuna** [comment]
Sorry, I posted the error message twice.  Here is the source:
![Source](https://user-images.githubusercontent.com/23587709/226480452-5ab4d77b-7d64-48ff-9632-08591308eae5.png)

**Comment by TBoyInPuna** [comment]
And here is the shell:
![Shell](https://user-images.githubusercontent.com/23587709/226481038-415a519a-e7b0-4ee2-8818-d17a20754986.png)

**Comment by TBoyInPuna** [comment]
I made some progress in diagnosing this.
The problem only occurs when the file being recognized is on a file server.  Recognition of the same file copied to a local drive works properly.
