### ISSUE TITLE
Problem with .so file.

### ISSUE THREAD

**Issue by marcosraul94** [acrcloud/acrcloud_sdk_python#18]
Hello, I installed successfully the package by running: `python -m pip install git+https://github.com/acrcloud/acrcloud_sdk_python` in a virtual env. But I'm getting this when I try to import ACRCloudRecognizer:

Python 3.8.0 (v3.8.0:fa919fdf25, Oct 14 2019, 10:23:27) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from acrcloud.recognizer import ACRCloudRecognizer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Work/env/lib/python3.8/site-packages/acrcloud/recognizer.py", line 21, in <module>
    import acrcloud_extr_tool
ImportError: dlopen(/Work/env/lib/python3.8/site-packages/acrcloud/acrcloud_extr_tool.so, 2): Symbol not found: _Py_InitModule4_64
  Referenced from: /Work/env/lib/python3.8/site-packages/acrcloud/acrcloud_extr_tool.so
  Expected in: flat namespace
 in /Work/env/lib/python3.8/site-packages/acrcloud/acrcloud_extr_tool.so

Any help will be appreciated. Thanks.

**Comment by JG87CH** [comment]
I have the same problem.

**Comment by qiuxuewen** [comment]
> Hello, I installed successfully the package by running: `python -m pip install git+https://github.com/acrcloud/acrcloud_sdk_python` in a virtual env. But I'm getting this when I try to import ACRCloudRecognizer:
> 
> Python 3.8.0 (v3.8.0:fa919fdf25, Oct 14 2019, 10:23:27)
> [Clang 6.0 (clang-600.0.57)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > from acrcloud.recognizer import ACRCloudRecognizer
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/Work/env/lib/python3.8/site-packages/acrcloud/recognizer.py", line 21, in 
> > > > import acrcloud_extr_tool
> > > > ImportError: dlopen(/Work/env/lib/python3.8/site-packages/acrcloud/acrcloud_extr_tool.so, 2): Symbol not found: _Py_InitModule4_64
> > > > Referenced from: /Work/env/lib/python3.8/site-packages/acrcloud/acrcloud_extr_tool.so
> > > > Expected in: flat namespace
> > > > in /Work/env/lib/python3.8/site-packages/acrcloud/acrcloud_extr_tool.so
> 
> Any help will be appreciated. Thanks.

Have fixed it, please try again.

**Comment by marcosraul94** [comment]
Yes, now it's working fine. Thanks, this can be closed.
