### ISSUE TITLE
issue with latest commit b9b6d28: DLL load failed while importing acrcloud_extr_tool: the specified module could not be found (Python 3.7, Windows 10)

### ISSUE THREAD

**Issue by mikemh-uri** [acrcloud/acrcloud_sdk_python#23]
after trying to run the most recent commit (b9b6d28) I got an error when I tried to import in python 3.7 on windows 10:
DLL load failed while importing acrcloud_extr_tool: the specified module could not be found 

so I had to download one of the older commits by doing pip install git+https@7517231 and it works, I haven't tested any other commits than those two but the most recent one isn't working.

**Comment by owlwang** [comment]
Have you installed the Windows Runtime Library? (In our README: https://github.com/acrcloud/acrcloud_sdk_python#windows-runtime-library)

You need to download the runtime and install:

https://www.microsoft.com/en-us/download/details.aspx?id=14632

**Comment by mikemh-uri** [comment]
> Have you installed the Windows Runtime Library? (In our README: https://github.com/acrcloud/acrcloud_sdk_python#windows-runtime-library)
> 
> You need to download the runtime and install:
> 
> https://www.microsoft.com/en-us/download/details.aspx?id=14632

Yes, I have installed those.
Still the version b9b6d28 does not work, but the 7517231 does.

**Comment by owlwang** [comment]
Sorry for the late reply. 
Can you try the latest commit?
We've fixed this problem.

**Comment by mikemh-uri** [comment]
> Sorry for the late reply.
> Can you try the latest commit?
> We've fixed this problem.

It's working now, thank you!
