### ISSUE TITLE
 No module named 'acrcloud_extr_tool' reinstalled but still getting this error

### ISSUE THREAD

**Issue by scrawford17** [acrcloud/acrcloud_sdk_python#24]
import acrcloud_extr_tool
ModuleNotFoundError: No module named 'acrcloud_extr_tool'
>>>

**Comment by owlwang** [comment]
You need to add 'acrcloud_extr_tool.so'  to your path.
Can you try to run the script?
https://github.com/acrcloud/acrcloud_sdk_python/blob/master/linux/x86-64/python3/test.py

**Comment by scrawford17** [comment]
i'm on windows 10 python3 and the script doesn't open :/

**Comment by owlwang** [comment]
Have you installed this library?


## Windows Runtime Library 
**If you run the SDK on Windows, you must install this library.**<br>
X86: [download and install Library(windows/vcredist_x86.exe)](https://www.microsoft.com/en-us/download/details.aspx?id=5555)<br>
x64: [download and install Library(windows/vcredist_x64.exe)](https://www.microsoft.com/en-us/download/details.aspx?id=14632)

**Comment by scrawford17** [comment]
yes i have :/

**Comment by owlwang** [comment]
Can you confirm whether your Python is 32-bit or 64 bit？
If you don't know, please install  32-bit and 64 bit vc++ runtime both.
And then try it again.
