### ISSUE TITLE
ImportError: DLL load failed on Windows 10 x64 with python 3.5.2

### ISSUE THREAD

**Issue by dofine** [acrcloud/acrcloud_sdk_python#3]
Run test with ` python test.py`:

``` 
import acrcloud_extr_tool
ImportError: DLL load failed: 找不到指定的模块。
```

Have followed all the instructions in the readme but no luck :(

`python` result:
```
Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32
```

Update:
Changed another windows PC and everything works fine now.
But still appreciate that if one could help dig what's wrong with the first develop environment. Thank you!

**Comment by qiuxuewen** [comment]
I have added the path of "acrcloud_extr_tool.pyd" which is Dll of "acrcloud_extr_tool"  module to "sys.path" in "__init__.py".
`sys.path.append(os.path.split(os.path.realpath(__file__))[0])`
Could you confirm again that the absolute path of "acrcloud_extr_tool.pyd" is in "sys.path".
