### ISSUE TITLE
(acrcloud_extra_tool.so) Unable to import shared object file: No such file or directory.

### ISSUE THREAD

**Issue by Sammyalhashe** [acrcloud/acrcloud_sdk_python#33]
Right now I am trying to import the recognizer module. I am running this on a raspberry pi running a 64bit version of manjaro inside of a virtual environment. The shared object file exists within the path it is trying to check, is this an indictment on the architecture I'm using and perhaps this shared object file is not compatible? 

I am currently using revision @686b935ddc9ba927a

**Comment by qiuxuewen** [comment]
You can download "https://github.com/acrcloud/acrcloud_sdk_python/tree/master/raspberrypi/aarch64" directly, and try "python test.py". If it also can't work, please send your OS download URL, and let me check it.
