### ISSUE TITLE
incompatible with >=python3.10

### ISSUE THREAD

**Issue by alex8msk** [acrcloud/acrcloud_sdk_python#36]
when I tried to create the fingerprint
f = acrcloud_extr_tool.create_fingerprint_by_file("/home/alex/Downloads/30-seconds-of-bluegrass-30-sec-challenge-4649.mp3",0, 6, False, 0)
I have the error: SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

**Comment by qiuxuewen** [comment]
> 

which library do you use?

**Comment by alex8msk** [comment]
pyacrcloud==1.0.2

**Comment by qiuxuewen** [comment]
You need to use github's library, do use "pip install".
