### ISSUE TITLE
Python 2.7: host not reachable

### ISSUE THREAD

**Issue by khalilhajji** [acrcloud/acrcloud_sdk_python#5]
{"status": {"msg": "http error:<urlopen error [Errno 8] nodename nor servname provided, or not known>", "code": 3000}}

the ns lookup on my host (us-west-2.api.acrcloud.com) does not resolve neither. However, even when I put the IP address instead of the host in config, I get the same error.

>> python test.py "path_to_song"
{"status": {"msg": "http error:<urlopen error [Errno 8] nodename nor servname provided, or not known>", "code": 3000}}
{"status": {"msg": "http error:<urlopen error [Errno 8] nodename nor servname provided, or not known>", "code": 3000}}

Here is my config
config = {
        'host':'52.24.23.208',
        'access_key':'MY_KEY',
        'access_secret':'MY_SECRET_KEY',
        'recognize_type': ACRCloudRecognizeType.ACR_OPT_REC_AUDIO, # you can replace it with [ACR_OPT_REC_AUDIO,ACR_OPT_REC_HUMMING,ACR_OPT_REC_BOTH], The     SDK decide which type fingerprint to create accordings to "recognize_type".
        'debug':False,
        'timeout':10 # seconds
    }

**Comment by khajji** [comment]
I am still having the same issue
