### ISSUE TITLE
acrcloud_extr_tool

### ISSUE THREAD

**Issue by DrUlysses** [acrcloud/acrcloud_sdk_python#9]
I'm using PyCharm and have installed acrcloud, like it is written in the guide, using pip. I have vcredist as well, but I become such error as I try to run the code:

```
 File "D:\Python\lib\site-packages\acrcloud\recognizer.py", line 21, in <module>
    import acrcloud_extr_tool
ModuleNotFoundError: No module named 'acrcloud_extr_tool'
```

**Comment by olym** [comment]
Is there some errors when you run "python setup.py install"?

**Comment by DrUlysses** [comment]
I'm runnung python -m pip install git+https://github.com/acrcloud/acrcloud_sdk_python and tried --upgrade as well. 
![image](https://user-images.githubusercontent.com/8532343/39619282-9442ba1c-4f87-11e8-8fa4-cc5e599177f3.png)
![image](https://user-images.githubusercontent.com/8532343/39619314-aff69d46-4f87-11e8-9d4d-085d06b3c324.png)

**Comment by qiuxuewen** [comment]
The setup file has some issues that I have fixed, please retry it.
Thanks.

**Comment by DrUlysses** [comment]
Thanks!
